### ISSUE TITLE
What license are these released under?

### ISSUE THREAD

**Issue by spuder** [geekhack-org/kicad-library#1]
Thanks for sharing these kicad libraries. 

I'd like to replace the cherry mx libraries here with the ones you made. 

https://github.com/UltimateHackingKeyboard/ugl-kicad-libs/blob/master/ugl.pretty/Cherry_MX.kicad_mod

This is part of the Ultimate Hacking Keyboard. 

https://www.crowdsupply.com/ugl/ultimate-hacking-keyboard

Before I make any changes, I want to be deliberate on libraries to make sure the keyboard remains completely free. What license are these libraries released under?

**Comment by worldspawn00** [comment]
The ones I picked up were from geek hack which are under an open license
iirc, the ones I made are completely open license, please felt free to
share.

**Comment by spuder** [comment]
Great thanks!

**Comment by komar007** [comment]
Hello spuder,

as far as I remember the footprints in this repository were drawn by me during work on GH60, and I consider them to be public domain. Feel free to use;)

Best regards,
Michał
